import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-white dark:bg-zinc-900 border-b border-gray-200 dark:border-zinc-700 px-6 py-4">
          <div className="max-w-7xl mx-auto flex items-center justify-between">
            <a href="/" className="text-xl font-bold text-black dark:text-zinc-50 hover:text-blue-600 transition-colors">
              🏠 Restaurant Admin
            </a>
            <nav className="flex items-center space-x-6">
              <a href="/" className="text-gray-600 dark:text-zinc-400 hover:text-blue-600 transition-colors">
                Dashboard
              </a>
              <a href="/orders" className="text-gray-600 dark:text-zinc-400 hover:text-blue-600 transition-colors">
                Orders
              </a>
              <a href="/menu-admin" className="text-gray-600 dark:text-zinc-400 hover:text-blue-600 transition-colors">
                Menu
              </a>
              <a href="/analytics" className="text-gray-600 dark:text-zinc-400 hover:text-blue-600 transition-colors">
                Analytics
              </a>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
